### ISSUE TITLE
CI: timeout connecting to WebDriver Server

### ISSUE THREAD

**Issue by olleolleolle** [gustafnk/h-include#46]
Build which failed: https://travis-ci.org/gustafnk/h-include/builds/384772141 

```
npm run server > /dev/null 2>&1 &
PORT=8080 node index.js 
(node:2807) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Starting browser firefox latest on Windows
Somewhere an unhandled exception screams
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:59755/hub
    at onError (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/http/util.js:87:11)
    at ManagedPromise.invokeCallback_ (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at new Driver (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/firefox/index.js:386:38)
    at Builder.build (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/builder.js:467:16)
    at Builder.buildAsync (/home/travis/build/gustafnk/h-include/node_modules/selenium-webdriver/builder.js:504:23)
    at Object.start (/home/travis/build/gustafnk/h-include/test/framework.js:36:8)
    at testBrowser (/home/travis/build/gustafnk/h-include/test/index.js:65:19)
    at /home/travis/build/gustafnk/h-include/test/index.js:47:11
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.

```

**Comment by gustafnk** [comment]
Fixed with https://github.com/gustafnk/h-include/pull/53
